
[workspace]
resolver = "3"
members = [
  "edlc_core",
  "edlc_codegen_cranelift",
  "edlc_docs",
  "edlc_layout",
  "edlc_lsp",
  "edlc_analysis",
]

[workspace.package]
version = "0.1.1"
repository = "https://github.com/LateinCecer/edlc"
authors = ["Adrian Paskert"]
license = "Apache-2.0"

